[build]
  command = "vite build"
  functions = "netlify/functions"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Sec-Fetch-Mode = "no-cors"

[[redirects]]
  from = "/api"
  to = "es.besoccer.com/equipo/america-cali:splat"
  status = 200


[[redirects]]
  from = "/nitter"
  to = "https://nitter.net/AmericadeCali/rss"
  status = 200

[[redirects]]
  from = "/america/*"
  to = "https://www.americadecali.co/:splat"
  status = 200